
name: Build Storybook

on:
  push:
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate static vuepress files
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run build-storybook -- -o ./docs

    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: commit
      run: |
        git add docs
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated add listing.json from Github actions"
            git push
          else
            echo "no changes";
          fi
