name: Build Storybook

on:
  push:
    branches:
      - "fix-gh-pages-storybook-errors"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build StoryBook production
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run deploy-storybook -- --ci --host-token-env-variable=GITHUB_TOKEN
